### ISSUE TITLE
Реализовать интерфейс главной формы

### ISSUE THREAD

**Issue by OlyaBershka** [pi18a-group-dynamics/First-Team#3]
1. Создать главное меню с "Рецептами","Категориями" и "Ингредиенты" 

2. Все рецепты разместить в выпадающем списке категорий.

3.  При выборе рецепта выводить предварительный его просмотр (фотография, ингредиенты и алгоритм приготовления).

4. Создать кнопку открытия рецепта с подробным описанием алгоритма приготовления.

5. Создать кнопку Фильтр(отбор данных по категории, ингредиентам).

6. Реализовать избранность блюд, а также удаление избранности.

7. Если блюдо избранное, то оно должно храниться в списке сверху.

**Comment by KirillDanilchuk** [comment]
Completed
