### ISSUE TITLE
Реализовать форму редактирования ингредиентов

### ISSUE THREAD

**Issue by Null410** [pi18a-group-dynamics/First-Team#6]
1. Создать таблицу для отображения ингредиентов:
- номер ингредиента;
- название ингредиента;
- мера ингредиента;
2. Для добавления нового ингредиента, а также изменения или удаления существующего добавить:
- поле "Название ингредиента";
- поле "Мера ингредиента";
- кнопку "Добавить";
- кнопку "Изменить";
- кнопку "Удалить".
3. Реализовать добавление нового ингредиента в базу данных.
4. Реализовать удаление ингредиента из базы данных (а также удаление всех рецептов, включающих его).
5. Реализовать изменение параметров существующего ингредиента.
5. Предусмотреть оповещение пользователя при удалении существующего ингредиента.

**Comment by KirillDanilchuk** [comment]
Completed.
